### PR TITLE
updated branch

### PR DESCRIPTION
**Pull request by MichelleGjolberg**
## Endringstype.
- slack-bot

## Linke til oppgave (Notion).
link her
## Beskrivelse.
endret branch, ikke merge meg - skal teste dismissed

### CODE REVIEW

**Review by emilaukner — CHANGES_REQUESTED** [review]
something

**Review by emilaukner — DISMISSED** [review]
nope

**Review by MichelleGjolberg — COMMENTED** [review]
please work

**Review by MichelleGjolberg — COMMENTED** [review]
please work

**Review by MichelleGjolberg — COMMENTED** [review]
Comments now work:))

**Pull request merged**
